services:
  chat-svc:
    image: tuananh1001lk/thanos-svc:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    deploy:
      replicas: 3
    ports:
      - "3000-3002:3000"
    networks:
      - vps-net

  chat-web:
    image: tuananh1001lk/thanos-web:latest
    depends_on:
      - chat-svc
    ports:
      - "5173:80"
    networks:
      - vps-net

networks:
  vps-net:
    external: true
