services:
  chat-svc:
    image: tuananh1001lk/thanos-svc:latest
    environment:
      - DATABASE_URL=mongodb://admin:123456@mongo:27017/thanos?authSource=admin&replicaSet=rs0&directConnection=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=change-me
    deploy:
      replicas: 3
    ports:
      - "3000-3009:3000"
    networks:
      - vps-net

  chat-web:
    image: tuananh1001lk/thanos-web:latest
    depends_on:
      - chat-svc
    ports:
      - "5173:80"
    networks:
      - vps-net

networks:
  vps-net:
    external: true
